settings.tex="lualatex";
settings.outformat="pdf";
texpreamble("\usepackage{fontspec}\usepackage{unicode-math}\setmainfont{Libertinus Serif}\setmathfont{Libertinus  Math}");
defaultpen(fontsize(9pt));
import geometry;
size(5cm);
draw(origin -- (3, 0), Arrow);
draw(origin -- (0, 3), Arrow);
draw((-1, 3) -- (3, -1), Arrows);
draw((1, 1) -- (1, 0));
label("$O$", origin, SW);
label("$X$", (3, 0), E);
label("$Y$", (0, 3), N);
label("$P(x, y)$", (1, 1), NE);
label("$y$", (1, 0.5), E);
label("$L$", (1, 0), S);
label("$Q$", (2, 0), S);
label("$R$", (0, 2), W);
label("$x$", (0.5, 0), S);
dot((-.7, 2.7));
dot((2.7, -.7));
label("$B$", (-.7, 2.7), S);
label("A", (2.7, -.7), S);
