settings.tex="lualatex";
settings.outformat="pdf";
texpreamble("\usepackage{fontspec}\usepackage{unicode-math}\setmainfont{Libertinus Serif}\setmathfont{Libertinus  Math}");
defaultpen(fontsize(9pt));
import geometry;
size(5cm);
draw(origin -- (4, 0), Arrow);
draw(origin -- (0, 4), Arrow);
draw((-1, 4) -- (4, -1), Arrows);
label("$O$", origin, SW);
label("$X$", (4, 0), E);
label("$Y$", (0, 4), N);
label("$P(x, y)$", (1, 2), NE);
label("$Q(x_1, y_1)$", (2, 1), NE);
draw((1, 2) -- (1, 0));
draw((2, 1) -- (2, 0));
draw((2, 1) -- (1, 1));
label("$B$", (-.7, 3.7), S);
label("$A$", (3.7, -.7), W);
dot((-.7, 3.7));
dot((3.7, -.7));
label("$L$", (1, 0), S);
label("$M$", (2, 0), S);
label("$H$", (3, 0), S);
label("$K$", (1, 1), W);
markangle("$\theta$", radius=5, (4, 0), (3, 0), (-1, 4));
markangle("$\pi - \theta$", radius=5, (1, 2), (2, 1), (1, 1));
