settings.tex="lualatex";
settings.outformat="pdf";
texpreamble("\usepackage{fontspec}\usepackage{unicode-math}\setmainfont{XCharter}\setmathfont{XCharter Math}");
defaultpen(fontsize(9pt));
import geometry;
size(5cm);
draw((-2, 0) -- (4, 0), Arrows);
draw((0, -1) -- (0, 4), Arrows);
draw((-1, 4) -- (4, -1), Arrows);
label("$O$", origin, SW);
label("$X$", (4, 0), E);
label("$Y$", (0, 4), N);
label("$X'$", (-2, 0), W);
label("$Y'$", (0, -1), S);
draw((3, 4) -- (-2, -1), Arrows);
label("$P$", (1, 2), N);
label("$A$", (-.6, 3.6), S);
label("$B$", (3.6, -.6), N);
dot((-.6, 3.6));
dot((3.6, -.6));
label("$C$", (2.6, 3.6), S);
label("$D$", (-1.4, -.4), S);
dot((2.6, 3.6));
dot((-1.4, -.4));
label("$L$", (3, 0), S);
label("$M$", (-1, 0), S);
markangle("$\alpha$", radius=5, (4, 0), (3, 0), (1, 2));
markangle("$\beta$", radius=5, (4, 0), (-1, 0), (1, 2));
markangle("$\phi$", radius=5, (3, 0), (1, 2), (2.6, 3.6));
markangle("$\psi$", radius=5, (-1, 0), (1, 2), (3, 0));
