settings.tex="lualatex";
settings.outformat="pdf";
texpreamble("\usepackage{fontspec}\usepackage{unicode-math}\setmainfont{Libertinus Serif}\setmathfont{Libertinus  Math}");
defaultpen(fontsize(9pt));
import geometry;
size(7cm);
draw((0, 0) -- (4, 0), Arrow);
draw((0, 0) -- (0, 4), Arrow);
draw((-1, 4) -- (4, -1), Arrows);
label("$O$", origin, SW);
label("$X$", (4, 0), E);
label("$Y$", (0, 4), N);
draw((1, 3) -- (1, 0));
label("$P(\alpha, \beta)$", (1, 3), E);
label("$R(\alpha_1, \beta_1)$", (1, 2), E);
label("$Q$", (1, 0), S);
dot((1, 3));
label("$A$", (-.3, 3.3), S);
dot((-.3, 3.3));
label("$B$", (3.3, -.3), S);
dot((3.3, -.3));

point z = (6,  0);
draw((0, 0) + z -- (4, 0) + z, Arrow);
draw((0, 0) + z -- (0, 4) + z, Arrow);
draw((-1, 4) + z -- (4, -1) + z, Arrows);
label("$O$", origin  + z, SW);
label("$X$", (4, 0) + z, E);
label("$Y$", (0, 4) + z, N);
draw((1, 2) + z -- (1, 0) + z);
label("$P(\alpha, \beta)$", (1, 1.1) + z, E);
label("$R(\alpha_1, \beta_1)$", (1, 2) + z, E);
label("$Q$", (1, 0) + z, S);
dot((1, 1.1) + z);
label("$A$", (-.3, 3.3) + z, S);
dot((-.3, 3.3) + z);
label("$B$", (3.3, -.3) + z, S);
dot((3.3, -.3) + z);
