settings.tex="lualatex";
settings.outformat="pdf";
texpreamble("\usepackage{fontspec}\usepackage{unicode-math}\setmainfont{Libertinus Serif}\setmathfont{Libertinus Math}");
defaultpen(fontsize(9pt));
import geometry;
size(5cm);
draw((0, 0) -- (4, 0), Arrow);
draw((0, 0) -- (0, 4), Arrow);
draw((-1, 4) -- (4, -1), Arrows);
label("$O$", origin, SW);
label("$X$", (4, 0), E);
label("$Y$", (0, 4), N);
draw((1, 2) -- (2, 3));
label("$P(\alpha, \beta)$", (2, 3), N);
draw((2, 3) -- (0, 3));
draw((2, 3) -- (3, 0));
label("$B$", (0, 3), W);
label("$A$", (3, 0), S);
line l1 = line((1, 2), (2, 3));
line l2 = line((1, 2), (3, 0));
perpendicularmark(l1, l2, quarter=4);
label("$M$", (1, 2), SW);
