settings.tex="lualatex";
settings.outformat="pdf";
texpreamble("\usepackage{fontspec}\usepackage{unicode-math}\setmainfont{Libertinus Serif}\setmathfont{Libertinus  Math}");
defaultpen(fontsize(9pt));
import geometry;
size(6cm);
draw((-4, 0) -- (4, 0), Arrow);
draw((0, -4) -- (0, 4), Arrow);
draw((-1, 4) -- (4, -1), Arrows);
draw((-1, -2) -- (4, 3), Arrows);
label("$O$", origin, SW);
label("$X$", (4, 0), E);
label("$Y$", (0, 4), N);
label("$X'$", (-4, 0), W);
label("$Y'$", (0, -4), S);
label("$A$", (-1, 4), NW);
label("$B$", (4, -1), SE);
label("$C$", (-1, -2), SW);
label("$D$", (4, 3), NE);
draw((-3, 1) -- (3, 1), Arrows);
draw((2, -3) -- (2, 3), Arrows);
label("$L$", (-3, 1), W);
label("$M$", (3, 1), E);
label("$R$", (2, -3), S);
label("$S$", (2, 3), N);
draw((0, 1) -- (1, 2));
draw((0, 1) -- (1, 0));
label("$P(x, y)$", (0, 1), N);
