settings.tex="lualatex";
settings.outformat="pdf";
texpreamble("\usepackage{fontspec}\usepackage{unicode-math}\setmainfont{XCharter}\setmathfont{XCharter Math}");
defaultpen(fontsize(9pt));
import geometry;
size(6cm);
unitsize(0.5cm);
draw((-3, 0) -- (3, 0), Arrows);
draw((0, -3) -- (0, 3), Arrows);
draw((1, 2) -- (-2, -1), Arrows);
markangle("$45^\circ$", radius=5, origin, (-1, 0), (1, 2));
point z = (8, 0);
draw((-3, 0) + z -- (3, 0) + z, Arrows);
draw((0, -3) + z -- (0, 3) + z, Arrows);
draw((2, -1) + z -- (-2, 3) + z, Arrows);
markangle("$135^\circ$", radius=5, (2, 0) + z, (1, 0) + z, (-2, 3) + z);
label("$X$", (3, 0), E);
label("$X'$", (-3, 0), W);
label("$Y$", (0, 3), N);
label("$Y'$", (0, -3), S);
label("$A$", (-1, 0), S);
label("$B$", (0, 1), E);
label("$X$", (3, 0) + z, E);
label("$X'$", (-3, 0) + z, W);
label("$Y$", (0, 3) + z, N);
label("$Y'$", (0, -3) + z, S);
label("$A$", (1, 0) + z, S);
label("$B$", (0, 1) + z, E);
