settings.tex="lualatex";
settings.outformat="pdf";
texpreamble("\usepackage{fontspec}\usepackage{unicode-math}\setmainfont{Libertinus Serif}\setmathfont{Libertinus Math}");
defaultpen(fontsize(9pt));
import geometry;
size(6cm);
unitsize(1cm);
draw((-2, 0) -- (5, 0), Arrows);
draw((0, -2) -- (0, 5), Arrows);
label("$X$", (5, 0), E);
label("$X'$", (-2, 0), W);
label("$Y$", (0, 5), N);
label("$Y'$", (0, -2), S);

draw((-1, 5) -- (5, -1), Arrows);
label("$B$", (-1, 5), NW);
label("$A$", (5, -1), SE);
draw((1, 3) -- (1, 0));
draw((2, 2) -- (2, 0));
draw((3, 1) -- (3, 0));
draw((2, 2) -- (1, 2));
draw((3, 1) -- (2, 1));
label("$O$", origin, SW);
label("$L$", (1, 0), S);
label("$M$", (2, 0), S);
label("$N$", (3, 0), S);
label("$H$", (1, 2), W);
label("$K$", (2, 1), W);
label("$P(x, y)$", (1, 3), E);
label("$Q(x_1, y_1)$", (2, 2), E);
label("$R(x_2, y_2)$", (3, 1), E);
